version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Service_Form
    volumes:
      - ./src:/src  
    working_dir: /src
    ports:
      - "8501:8501" 
    command: ["streamlit","run", "/src/main.py"]